easy_admin:
    site_name: '<img src="https://res.cloudinary.com/hrscywv4p/image/upload/c_limit,fl_lossy,h_300,w_300,f_auto,q_auto/v1/1391026/head_b7uqte.png"/>'
    user:
        name_property_path: 'username'
        display_avatar: false

    list:
        title: 'Liste des %%entity_label%%'
    design:
        assets:
            # all kinds of assets are supported and linked accordingly
            css:
                - '//example.org/css/admin1.css'
                - 'http://example.org/css/admin2.css'
                - 'https://example.org/css/admin3.css'
                - '/bundles/user/css/admin4.css'
                - 'bundles/app/css/admin5.css'
                - 'bundles/easyadmin/bootstrap-all.css'
                - 'css/admin.css'
            js:
                - '//example.org/js/admin1.js'
                - 'http://example.org/js/admin2.js'
                - 'https://example.org/js/admin3.js'
                - '/bundles/user/js/admin4.js'
                - 'bundles/app/js/admin5.js'
                - 'bundles/easyadmin/bootstrap-all.js'
            favicon: 'images/favicon.jpeg'

        brand_color: '#0cc5b9 !important'
        menu:
            - { label: 'Menu' }
            - { entity: 'User', icon: 'user' }
            - { entity: 'Box', icon: 'square' }
    entities:
        # List the entity class name you want to manage
        User:
            class: App\Entity\User
            list:
                sort: ['id', 'ASC']
                fields: ['id', 'username', 'email', 'roles']
        Box:
            class: App\Entity\Box
            list:
                sort: ['id', 'ASC']
                fields: ['id', 'name', 'price']
